# Generated by Django 4.1.1 on 2022-09-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Категория товара: ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара: ', max_length=100)),
                ('description', models.TextField(help_text='Описание товара: ')),
                ('currency', models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('₽', 'rubles')], max_length=1)),
                ('price', models.FloatField(help_text='Цена товара: ')),
                ('size', models.CharField(blank=True, help_text='Размер товара: ', max_length=100, null=True)),
                ('main_image', models.ImageField(upload_to='media/', verbose_name='Главное изображение товара: ')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара: ')),
                ('category', models.ForeignKey(help_text='Категория товара: ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.typeproduct', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
