# Generated by Django 4.1.1 on 2022-09-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'ordering': ['category_name'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товара'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.typeproduct', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('D', 'Dollar'), ('E', 'Euro'), ('R', 'Rubles')], max_length=1, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Дополнительное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='media/', verbose_name='Главное изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер товара'),
        ),
    ]
